import {
  AreaChart,
  BarChart,
  BoxPlotSeries,
  BubbleSeries,
  Button,
  CandleStickSeries,
  Card,
  Contact,
  DonutSeries,
  Error,
  Features,
  Footer,
  Form,
  Gallery,
  Home,
  LineChart,
  Navbar,
  PieChart,
  Portfolio,
  ScatterSeries,
  Steps,
  Testimonials,
} from "../playground/index";

export const codeMapping = {
  card: Card,
  barchart: BarChart,
  button: Button,
  donutseries: DonutSeries,
  footer: Footer,
  linechart: LineChart,
  navbar: Navbar,
  piechart: PieChart,
  scatterseries: ScatterSeries,
  areachart: AreaChart,
  bubble: BubbleSeries,
  boxplot: BoxPlotSeries,
  candlelist: CandleStickSeries,
  form: Form,
  error: Error,
  portfolio: Portfolio,
  contact: Contact,
  features: Features,
  gallery: Gallery,
  home: Home,
  testimonials: Testimonials,
  steps: Steps,
};
