export const links = [
  { name: "", description: "Follow for updates", identifier: "@manish" , identifiers:"@sagar" },
  // { name: "Installation", steps: ["Install Next.js", "Install Tailwind CSS", "Add utilities"] },
  { name: "", description: "All Components" },
  { name: "3D Card Effect", category: "3D Effects" },
  { name: "3D Pin", category: "3D Effects" },
  { name: "Animated Modal", category: "Animation" },
  { name: "Animated Testimonials", category: "Animation" },
  { name: "Animated Tooltip", category: "Animation" },
  { name: "Apple Cards Carousel", category: "Carousel" },
  { name: "Aurora Background", category: "Background Effects" },
  { name: "Background Beams", category: "Background Effects" },
  { name: "Background Beams With Collision", category: "Background Effects" },
  { name: "Background Boxes", category: "Background Effects" },
  { name: "Background Gradient", category: "Background Effects" },
  { name: "Background Lines", category: "Background Effects" },
  { name: "Bento Grid", category: "Grid Layouts" },
  { name: "Canvas Reveal Effect", category: "Canvas Effects" },
  { name: "Card Hover Effect", category: "Card Effects" },
  { name: "Card Spotlight", category: "Card Effects" },
  { name: "Card Stack", category: "Card Effects" },
  { name: "Cards", category: "Card Effects" },
  { name: "Compare", category: "Comparisons" },
  { name: "Container Cover", category: "Container Effects" },
  { name: "SVG Mask Effect", category: "SVG Effects" },
  
  ];